INSERT INTO `customer`(id,first_name,last_name,email) VALUES (1,'David','Adams','david@luv2code.com')
INSERT INTO `customer`(id,first_name,last_name,email) VALUES(2,'John','Doe','john@luv2code.com')
	INSERT INTO `customer`(id,first_name,last_name,email) VALUES(3,'Ajay','Rao','ajay@luv2code.com')
	INSERT INTO `customer`(id,first_name,last_name,email) VALUES(4,'Mary','Public','mary@luv2code.com')
	INSERT INTO `customer`(id,first_name,last_name,email) VALUES(5,'Maxwell','Dixon','max@luv2code.com')